/**
 * 思维导图节点过滤规则
 *
 * 目标：减少杂音文件，让思维导图聚焦于有意义的项目文件。
 * 后续会接入 AI 做智能挑选，本模块提供本地兜底规则。
 */

import type { DirNode } from "@/types/directory";

// ============================================================
// 类型
// ============================================================

export interface FilterResult {
  /** 保留的节点 */
  kept: DirNode[];
  /** 被过滤掉的节点（可用于日志） */
  removed: string[];
}

// ============================================================
// 入口：对一组兄弟节点依次应用全部规则
// ============================================================

/**
 * 过滤一个目录下的子节点。
 * 目录本身永远不受影响（只过滤文件）。
 */
export function filterChildren(children: DirNode[]): FilterResult {
  let pool = children;
  const removed: string[] = [];
  const ruleStats: string[] = [];

  // 各规则按顺序执行（每个规则处理后返回新的 pool）
  const rules: Array<{ name: string; fn: (nodes: DirNode[]) => FilterResult }> = [
    { name: "system", fn: removeSystemFiles },
    { name: "autoGenerated", fn: removeAutoGenerated },
    { name: "repetitive", fn: removeRepetitive },
  ];

  for (const rule of rules) {
    const before = pool.length;
    const result = rule.fn(pool);
    pool = result.kept;
    for (const r of result.removed) {
      removed.push(`[${rule.name}] ${r}`);
    }
    if (result.removed.length > 0) {
      ruleStats.push(`${rule.name}:${result.removed.length}(${before}→${pool.length})`);
    }
  }

  if (ruleStats.length > 0) {
    console.log("[Filter] 过滤完成:", ruleStats.join(", "));
  }

  return { kept: pool, removed };
}

// ============================================================
// 规则 1：系统文件 / 隐藏文件 / 备份文件
// ============================================================

const SYSTEM_PATTERNS: Array<{ test: (name: string) => boolean; label: string }> = [
  {
    test: (n) => /^\./.test(n),
    label: "隐藏文件",
  },
  {
    test: (n) => /^Thumbs\.db$/i.test(n) || /^desktop\.ini$/i.test(n) || /^\.DS_Store$/.test(n),
    label: "系统残留",
  },
  {
    test: (n) => /\.bak$/i.test(n) || /\.tmp$/i.test(n) || /\.old$/i.test(n) || /~$/.test(n),
    label: "备份/临时文件",
  },
  {
    test: (n) => /\.map$/i.test(n) && !/\.js\.map$/.test(n),
    label: "sourcemap",
  },
];

function removeSystemFiles(nodes: DirNode[]): FilterResult {
  const kept: DirNode[] = [];
  const removed: string[] = [];

  for (const node of nodes) {
    if (!node.isDir) {
      let skip = false;
      for (const p of SYSTEM_PATTERNS) {
        if (p.test(node.name)) {
          removed.push(node.name);
          skip = true;
          break;
        }
      }
      if (!skip) kept.push(node);
    } else {
      kept.push(node); // 目录永远保留
    }
  }

  return { kept, removed };
}

// ============================================================
// 规则 2：自动生成的文件名（相机 / 截图 / hash / 流水号）
// ============================================================

/**
 * 检测文件名是否像自动生成的（无人类可读含义）。
 */
function looksAutoGenerated(name: string): boolean {
  const base = name.replace(/\.[^.]+$/, ""); // 去掉扩展名

  // 相机/手机默认命名
  if (/^(IMG|VID|PXL|PANO|MOV|DSC|DSCF|DSCN|SAM|MAH|MVI|PICT)_\d/i.test(base))
    return true;

  // 截图
  if (/^(截图|Screenshot|Screen ?Shot|屏幕截图|Snipaste|Capture|截屏)/i.test(base))
    return true;

  // 录屏
  if (/^(录屏|Screen ?[Rr]ecord(ing)?|Record(ing)?)/i.test(base))
    return true;

  // 微信/QQ 等聊天工具图片
  if (/^(mmexport|wx_camera|microMsg\.|QQ图片|QQ视频)/i.test(base))
    return true;

  // 纯日期时间命名 (2024-01-01, 20240101_xxx)
  if (/^\d{4}[-_]?\d{2}[-_]?\d{2}[ _-]?\d{0,6}/.test(base) && base.length <= 20)
    return true;

  // 纯数字序列 (00001, 0001_xxx)
  if (/^\d{4,}$/.test(base))
    return true;

  // base64/hash 风格 (8+ 位无意义的字母数字)
  if (/^[a-f0-9]{20,}$/i.test(base))
    return true;

  // Untitled / 未命名 / 新建 系列
  if (/^(未命名|新建|无标题|Untitled|New|空白)\b/i.test(base))
    return true;

  // 纯UUID
  if (/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(base))
    return true;

  return false;
}

function removeAutoGenerated(nodes: DirNode[]): FilterResult {
  const kept: DirNode[] = [];
  const removed: string[] = [];

  for (const node of nodes) {
    if (!node.isDir && looksAutoGenerated(node.name)) {
      removed.push(node.name);
    } else {
      kept.push(node);
    }
  }

  return { kept, removed };
}

// ============================================================
// 规则 3：同目录内重复关键词（前缀 + 后缀）
// ============================================================

/**
 * 在同级文件中检测"大量重复前后缀"模式。
 * 例如：
 *   前缀：显卡日报数据库0409.xlsx, 显卡日报数据库0410.xlsx, ...
 *   后缀：202401_report.xlsx, 202402_report.xlsx, ...
 * 当有 N 个文件共享相同前缀或后缀（长度 > 阈值），认为是批量生成的。
 */

const REPETITIVE_MIN_COUNT = 4;
const AFFIX_MIN_LENGTH = 5; // 前缀/后缀最短长度

function removeRepetitive(nodes: DirNode[]): FilterResult {
  const files = nodes.filter((n) => !n.isDir);
  if (files.length < REPETITIVE_MIN_COUNT) return { kept: nodes, removed: [] };

  // 去掉扩展名的基底
  const items = files.map((f) => ({
    node: f,
    base: f.name.replace(/\.[^.]+$/, ""),
  }));

  const repetitivePaths = new Set<string>();

  // --- 共享前缀检测 ---
  detectByAffix(items, "prefix", repetitivePaths);
  // --- 共享后缀检测 ---
  detectByAffix(items, "suffix", repetitivePaths);

  const kept: DirNode[] = [];
  const removed: string[] = [];
  for (const node of nodes) {
    if (repetitivePaths.has(node.path)) {
      removed.push(node.name);
    } else {
      kept.push(node);
    }
  }

  return { kept, removed };
}

/** 按前缀或后缀分组，标记重复组 */
function detectByAffix(
  items: Array<{ node: DirNode; base: string }>,
  mode: "prefix" | "suffix",
  out: Set<string>,
) {
  // 对每个基底取所有 >= AFFIX_MIN_LENGTH 的前缀/后缀，建立倒排索引
  const index = new Map<string, string[]>(); // affix → file paths

  for (const { node, base } of items) {
    if (mode === "prefix") {
      // 前缀：取前 AFFIX_MIN_LENGTH 个字符作为分组 key
      if (base.length >= AFFIX_MIN_LENGTH) {
        const key = base.substring(0, AFFIX_MIN_LENGTH);
        const list = index.get(key) ?? [];
        list.push(node.path);
        index.set(key, list);
      }
    } else {
      // 后缀：取从位置 i 开始到末尾的每个片段（>= AFFIX_MIN_LENGTH）
      for (let i = 0; i <= base.length - AFFIX_MIN_LENGTH; i++) {
        const slice = base.substring(i);
        const list = index.get(slice) ?? [];
        list.push(node.path);
        index.set(slice, list);
      }
    }
  }

  // 对每组 >= REPETITIVE_MIN_COUNT，保留一个代表，其余标记
  const keep = new Set<string>();
  for (const [, paths] of index) {
    if (paths.length >= REPETITIVE_MIN_COUNT) {
      keep.add(paths[0]); // 每组保留第一个
    }
  }
  // 在组内但未被保留的 → 标记移除
  for (const [, paths] of index) {
    if (paths.length >= REPETITIVE_MIN_COUNT) {
      for (const p of paths) {
        if (!keep.has(p)) out.add(p);
      }
    }
  }
}
